### ISSUE TITLE
Exam 7

### ISSUE THREAD

**Issue by anarut** [breadKozlov/it_academy_zadachi#1]
https://github.com/breadKozlov/it_academy_zadachi/blob/8043716e09ac30476da0b90305974ae0281713df/src/exam/NaOzcenkuNumSeven.java#L63

зачем вам 2 цикл для нахождения коливхождений?

**Comment by breadKozlov** [comment]
ну это был метод поиска повторов, но реализованный через Могилев. Поправил, на поиск повторного ключа в самой мапке.
